### PR TITLE
Bug in `standardize_row_labels`

### PR DESCRIPTION
**Pull request by fcrimins**
Double standardization results in non-standard (e.g. /c//en_term) URIs.

### CODE REVIEW

**Comment by rspeer** [comment]
Avoiding double-standardization is a good idea. It can be idempotent, so it should be.

Is there a place in the build process where this is currently happening, or is it a precaution?

**Comment by fcrimins** [comment]
The new implementation is indeed idempotent if the URIs are already standardized.

I'm sorry, but I'm not familiar enough with the build process to say whether it's happening there or not.  I came across it while trying to run `convert_fasttext` on numberbatch-17.04.txt.gz which appears to contain standardized URIs.

**Comment by fcrimins** [comment]
I added another commit to this pull request.  Here's its commit message: 'Adds UTF-8 encoding declaration to nodes.py which contains a non-ASCII character in the word "über".'

**Comment by rspeer** [comment]
It's not necessary to declare the file to be in UTF-8 in Python 3 -- that's the default.

I don't actually recognize the format that this code is meant to convert. Was there a Numberbatch file that was labeled with a single slash in each label, like `en/example`? I double-checked both 17.02 and 17.04, and they're labeled with URIs in the appropriate form, like `/c/en/example`.

**Comment by fcrimins** [comment]
Oh, okay, I must have run once w/ Python 2 by mistake and seen the error.

I haven't come across the format that that code is meant to convert either.  It just improperly converts the properly standardized formats that already exist in 17.02 & 04.

**Comment by rspeer** [comment]
I don't think I understand this code and its comments, then.

When you say `now partitions label='en/term' into tuple=('en', '/', 'term') into new label=/c/en/term`, where did the string "en/term" come from? Why is this assuming that the labels can be partitioned at a single slash?

**Comment by fcrimins** [comment]
I inferred the "en/term" format from the existing code's behavior.  I've never actually seen a string with that format before.  The existing code doesn't work with correctly formatted URI strings, e.g. "/c/en/term", which is why I was inferring that it was meant to handle some other format.  The existing code would work properly however with the inferred format.  The bug then was that it wasn't properly distinguishing the inferred from the correct formats in this line `if all('/' in label for label in frame.index[10:20])` which is true for both, but which should only be true for the inferred.

**Comment by rspeer** [comment]
Okay, I understand now where this came from, and I see why this leads to a bug.

I now remember that the `en/term` format is the ad-hoc format we were using to train fastText on multilingual text from OpenSubtitles, which as of recently is one of our inputs. And this code is detecting that ad-hoc format when it shouldn't be.

**Comment by rspeer** [comment]
...to clarify, this code is designed to detect that ad-hoc format. It also erroneously detects it given standard ConceptNet URIs, and that's the bug.

**Comment by rspeer** [comment]
Anyway, this seems like the right plan, though I think the comments need some revising.

**Pull request merged**
